#!/bin/sh
# Script used to generate the orig source tarball for opp

OPP_GIT_URL="https://github.com/floomoon/opp.git"
OPP_VERSION="`cat VERSION | sed /^$/d`"

rm -rf "opp_${OPP_VERSION}"
git clone "$OPP_GIT_URL" "opp_${OPP_VERSION}"

echo "Moving git HEAD position to tag v${OPP_VERSION}"
cd "opp_${OPP_VERSION}" && git checkout v${OPP_VERSION} && cd ..

# Remove temp files and other cruft from source tarball
# The find command snippet here was taken from debhelper's dh_clean command
# with some modification to delete more unneeded files.
echo "Removing temp files and other cruft from source tarball"
find opp_${OPP_VERSION} \( \( -type f -a \
  \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
  -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
  -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
  -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
  -o -name config.status -o -name config.cache -o -name config.log \
  \) -exec rm -f "{}" \; \) -o \
  \( -type d -a -name autom4te.cache -prune -exec rm -rf "{}" \; \) \)
rm -rf opp_${OPP_VERSION}/.git
rm -f opp_${OPP_VERSION}/.gitignore
rm -rf opp_${OPP_VERSION}/debian
rm -rf opp_${OPP_VERSION}/Autobuild
rm -f opp_${OPP_VERSION}/Autobuild.sh

# Remove empty directories
echo "Removing empty directories from source"
find opp_${OPP_VERSION} -type d -empty -delete

tar --exclude-vcs -czf "opp_${OPP_VERSION}.orig.tar.gz" "opp_${OPP_VERSION}/"
rm -rf "opp_${OPP_VERSION}"
echo "Successfully packaged OPP sources v${OPP_VERSION} in opp_${OPP_VERSION}.orig.tar.gz"
